---

- name: Install podman
  ansible.builtin.include_role:
    name: osp.edpm.edpm_podman
    tasks_from: install.yml
  tags:
    - edpm_podman
    - download_cache

- name: Login to container registries if needed
  ansible.builtin.include_role:
    name: osp.edpm.edpm_podman
    tasks_from: login.yml
  tags:
    - edpm_podman
    - download_cache

- name: Download images for edpm_iscsid role
  ansible.builtin.include_role:
    name: osp.edpm.edpm_iscsid
    tasks_from: download_cache.yml
  tags:
    - edpm_iscsid
    - download_cache

- name: Download images for edpm_ovn role
  ansible.builtin.include_role:
    name: osp.edpm.edpm_ovn
    tasks_from: download_cache.yml
  tags:
    - edpm_ovn
    - download_cache
