---

- name: Install podman
  ansible.builtin.include_role:
    name: osp.edpm.edpm_podman
    tasks_from: install.yml
  tags:
    - edpm_podman
    - download_cache

- name: Login to container registries if needed
  ansible.builtin.include_role:
    name: osp.edpm.edpm_podman
    tasks_from: login.yml
  tags:
    - edpm_podman
    - download_cache


- name: Download images for edpm_nova role
  ansible.builtin.include_role:
    name: osp.edpm.edpm_nova
    tasks_from: download_cache.yml
  tags:
    - edpm_nova
    - download_cache
