---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure that 10-neutron-metadata.conf was copied into the container
      block:
        - name: metadata config file exists
          become: true
          ansible.builtin.stat:
            path: "/var/lib/config-data/ansible-generated/neutron-ovn-metadata-agent/10-neutron-metadata.conf"
          register: metadata_config

        - name: assert that the config exists
          ansible.builtin.assert:
            that:
              - metadata_config.stat.exists
            fail_msg: "metadata agent config file does not exist"
