---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: compute-1
    groups:
      - compute
provisioner:
  log: true
  name: ansible
  inventory:
    host_vars:
      compute-1:
        ctlplane_ip: "10.0.0.1"

scenario:
  test_sequence:
  - prepare
  - converge
  - verify
verifier:
  name: ansible
