---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: compute-1
  gather_facts: false
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
  tasks:
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_dir.yaml"
      loop:
        # common directories
        - "/etc/tmpfiles.d/"
        - "/var/lib/openstack"
        # extrenal deps
        - "/var/lib/openstack/config/ceph"
        # libvirt directories
        - "/var/lib/libvirt"
        - "/etc/libvirt"
    - name: ensure firewall is configured
      ansible.builtin.include_tasks: "test-helpers/verify_firewall.yaml"
    - name: ensure ceph secret is configured
      ansible.builtin.include_tasks: "test-helpers/verify_ceph_secret.yaml"
    - name: ensure systemd services are defined and functional
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        # rhel installed services have service units defiend via rpm in
        # /usr/lib/systemd/system so disable the check for them them in
        # /etc/systemd/system
        - { "name": "virtlogd.service", "osp_service": false, "enabled": "enabled" }
        - { "name": "virtnodedevd.service" , "osp_service": false, "enabled": "enabled", "active": ["active", "inactive"] }
        - { "name": "virtproxyd.service", "osp_service": false, "enabled": "enabled", "active": ["active", "inactive"] }
        - { "name": "virtqemud.service", "osp_service": false, "enabled": "enabled", "active": ["active", "inactive"] }
        - { "name": "virtsecretd.service", "osp_service": false, "enabled": "enabled", "active": ["active", "inactive"] }
    - name: ensure libvirt.target exist and are running
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        - { "name": "edpm_libvirt.target", "enabled": "static"}
        - { "name": "edpm_libvirt_guests.service", "running":false }
        - { "name": "virt-guest-shutdown.target", "enabled": "static", "running":false }
    - name: Check if user exists
      ansible.builtin.getent:
        database: passwd
        key: libvirt
      register: libvirt_user
    - name: Assert that libvirt user is created with kolla uid and gid
      ansible.builtin.assert:
        that:
          # user
          - "libvirt_user.ansible_facts.getent_passwd.libvirt[1] == '42473'"
          # group
          - "libvirt_user.ansible_facts.getent_passwd.libvirt[2] == '42473'"
    - name: ensure libvirt sockets are enabled
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        - { "name": "virtlogd-admin.socket", "osp_service": false }
        - { "name": "virtlogd.socket", "osp_service": false }
        - { "name": "virtnodedevd-admin.socket", "osp_service": false }
        - { "name": "virtnodedevd-ro.socket", "osp_service": false }
        - { "name": "virtnodedevd.socket", "osp_service": false }
        - { "name": "virtproxyd-admin.socket", "osp_service": false }
        - { "name": "virtproxyd-ro.socket", "osp_service": false }
        - { "name": "virtproxyd.socket", "osp_service": false }
        - { "name": "virtqemud-admin.socket", "osp_service": false }
        - { "name": "virtqemud-ro.socket", "osp_service": false }
        - { "name": "virtqemud.socket", "osp_service": false }
        - { "name": "virtsecretd-admin.socket", "osp_service": false }
        - { "name": "virtsecretd-ro.socket", "osp_service": false }
        - { "name": "virtsecretd.socket", "osp_service": false }


    - name: ensure libvirt socket activation drop-in directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_sockets_exits.yaml"
      loop:
        - {"path": "/run/libvirt/virtlogd-admin-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtlogd-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtnodedevd-admin-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtnodedevd-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtnodedevd-sock-ro", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtqemud-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtqemud-sock-ro", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtqemud-admin-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtsecretd-admin-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtsecretd-sock", "user": "root", "group": "libvirt" }
        - {"path": "/run/libvirt/virtsecretd-sock-ro", "user": "root", "group": "libvirt" }

    - name: ensure container_file_t selinux lable is not set on /run/libvirt
      ansible.builtin.shell: "ls -lZ /run/libvirt | grep container_file_t"
      register: run_libvirt
      failed_when: run_libvirt.rc not in [0, 1]
    - name: Assert that container_file_t selinux lable is not set on /run/libvirt
      ansible.builtin.assert:
        that:
          - "run_libvirt.rc != 0"

    - name: Load /etc/libvirt/qemu.conf
      ansible.builtin.shell: "grep migration_port /etc/libvirt/qemu.conf | tr '\n' ' '"
      register: qemu_conf_migration_ports
    - name: Assert that qemu.conf has a proper migration port range
      assert:
        that:
          - "item  == 'migration_port_min = 61152 migration_port_max = 61215 '"
      loop: "{{ qemu_conf_migration_ports.stdout_lines }}"
