- name: Verify libvirt sockets are created with correct permissions {{ item }}
  block:
    - name: Check that libvirt sockets exist {{ item }}
      become: true
      ansible.builtin.stat:
        path: "{{ item }}"
      register: socket_exists
    - name: Assert that libvirt sockets exist {{ item }}
      ansible.builtin.assert:
        that:
          - socket_exists.stat.exists
          - socket_exists.stat.issock
        fail_msg: "libvirt socket {{ item }} does not exist"
    - name: Assert that libvirt socket is owned by root and has libvirt group {{ item }}
      ansible.builtin.assert:
        that:
          - socket_exists.stat.pw_name == 'root'
          - socket_exists.stat.gr_name == 'libvirt'
        fail_msg: "libvirt socket {{ item }} is not owned by root:libvirt"
