- name: Get the mock FSID from ceph conf file
  become: true
  ansible.builtin.shell: |
    awk -F '=' '/fsid/ {print $2}' {{ conf_path }} | xargs
  vars:
    conf_path: /var/lib/openstack/config/ceph/ceph.conf
  register: fsid

- name: Get the mock cephx key from ceph keyring file
  become: true
  ansible.builtin.command: |
    awk '$1 == "key" {print $3}' {{ key_path }}
  vars:
    key_path: /var/lib/openstack/config/ceph/ceph.client.openstack.keyring
  register: cephx

- name: Get cephx key from libvirt_virtsecretd container by passing FSID
  become: true
  ansible.builtin.command: |
    podman exec libvirt_virtsecretd bash -c "virsh secret-get-value $FSID"
  environment:
    FSID: "{{ fsid.stdout }}"
  register: virsh_secret

- name: Assert that virsh secret-get-value returned the correct value
  ansible.builtin.assert:
    that:
      - virsh_secret.stdout == cephx.stdout
    fail_msg: "virsh secret-get-value {{ fsid.stdout }} return value is wrong"
