---
# defaults file for edpm_ovn
edpm_ovn_bridge: br-int
edpm_ovn_bridge_mappings: ["datacentre:br-ex"]
edpm_ovn_encap_type: geneve
edpm_ovn_dbs: []
edpm_enable_dvr: True
edpm_enable_hw_offload: False
edpm_ovn_multi_rhel: False
edpm_enable_internal_tls: False
edpm_ovn_sb_server_port: 6642
edpm_ovn_of_probe_interval: 60
edpm_ovn_remote_probe_interval: 60000
edpm_ovn_ofctrl_wait_before_clear: 8000
edpm_ovn_controller_image: "quay.io/edpmmastercentos9/openstack-ovn-controller:current-edpm"
edpm_ovn_encap_ip: "{{ tenant_ip }}"
edpm_ovn_protocol: "{% if edpm_enable_internal_tls | bool %}ssl{% else %}tcp{% endif %}"

edpm_ovn_controller_common_volumes:
  - /lib/modules:/lib/modules:ro
  - /run:/run
  - /var/lib/openvswitch/ovn:/run/ovn:shared,z
  - /var/log/containers/openvswitch:/var/log/openvswitch:z
  - /var/log/containers/openvswitch:/var/log/ovn:z
  - /var/lib/kolla/config_files/ovn_controller.json:/var/lib/kolla/config_files/config.json:ro

edpm_ovn_controller_tls_volumes:
  - /etc/pki/tls/certs/:/etc/pki/tls/certs/
  - /etc/pki/tls/private/:/etc/pki/tls/private/

# Set external_id data from provided variables
edpm_ovn_ovs_external_ids:
  hostname: "{{ ansible_facts['fqdn'] }}"
  ovn-bridge: "{{ edpm_ovn_bridge }}"
  ovn-bridge-mappings: "{{ edpm_ovn_bridge_mappings|join(', ') }}"
  ovn-encap-ip: "{{ edpm_ovn_encap_ip }}"
  ovn-encap-type: "{{ edpm_ovn_encap_type }}"
  ovn-match-northd-version: True
  ovn-monitor-all: True
  ovn-openflow-probe-interval: "{{ edpm_ovn_of_probe_interval }}"
  ovn-remote: "{% set db_addresses = [] %}{% for host in edpm_ovn_dbs %}{{ db_addresses.append([edpm_ovn_protocol, host, edpm_ovn_sb_server_port] | join(':')) }}{% endfor %}{{ db_addresses | join(',') }}"
  ovn-remote-probe-interval: "{{ edpm_ovn_remote_probe_interval }}"
  ovn-ofctrl-wait-before-clear: "{{ edpm_ovn_ofctrl_wait_before_clear }}"
  rundir: "/var/run/openvswitch"

# Set openvswitch other_config.
edpm_ovn_ovs_other_config:
  vlan-limit: 0
