---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: podman
platforms:
- command: /sbin/init
  dockerfile: ../../../../molecule/common/Containerfile.j2
  image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
  name: instance
  privileged: true
  pre_build_image: true
  registry:
    url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
  ulimits:
  - host
provisioner:
  log: true
  name: ansible
scenario:
  test_sequence:
  - destroy
  - create
  - prepare
  - converge
  - check
  - verify
  - destroy
verifier:
  name: ansible
