---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: podman
platforms:
- command: /sbin/init
  dockerfile: ../../../../molecule/common/Containerfile.j2
  image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
  name: instance
  privileged: true
  registry:
    url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
  ulimits:
  - host
provisioner:
  log: true
  name: ansible
  playbooks:
    converge: ${MOLECULE_SCENARIO_DIRECTORY}/../../resources/molecule/converge.yml
    prepare: ${MOLECULE_SCENARIO_DIRECTORY}/../../resources/molecule/prepare.yml
    verify: ${MOLECULE_SCENARIO_DIRECTORY}/../../resources/molecule/verify.yml
scenario:
  name: default
  test_sequence:
  - destroy
  - create
  - prepare
  - converge
  - idempotence
  - check
  - verify
  - destroy
verifier:
  name: ansible
