---
- name: Stop and disable compute services
  tags:
    - adoption
    - nova
  become: true
  ansible.builtin.shell: |
    if systemctl is-active {{ item }}; then
      systemctl disable --now {{ item }}
      test -f /etc/systemd/system/{{ item }} || systemctl mask {{ item }}
    fi
  loop: "{{ edpm_nova_old_tripleo_compute_sevices }}"
  failed_when: false
  changed_when: false
  when: edpm_nova_old_tripleo_compute_sevices | default([]) | length > 0
