---
- name: Stop and disable compute services
  tags:
    - adoption
    - nova
  ansible.builtin.include_role:
    role: osp.edpm.edpm_tripleo_cleanup
  vars:
    edpm_old_tripleo_services: "{{ edpm_nova_old_tripleo_compute_sevices }}"
  when: edpm_nova_old_tripleo_compute_sevices | default([]) | length > 0
