---
- name: Verify and stop nova_virtlogd
  become: true
  tags:
    - adoption
    - libvirt
  block:
    - name: Check if nova_virtlogd container exists
      ansible.builtin.command: podman ps -a --filter name=^nova_virtlogd$ --format \{\{.Names\}\}
      register: nova_virtlogd_status
      failed_when: false
      changed_when: false
    - name: Stop nova_virtlogd containers not managed by service units
      ansible.builtin.command: podman stop nova_virtlogd
      failed_when: false
      changed_when: false
      when: nova_virtlogd_status.stdout_lines | length > 0

- name: Stop and disable libvirt services
  tags:
    - adoption
    - libvirt
  ansible.builtin.include_role:
    role: osp.edpm.edpm_tripleo_cleanup
  vars:
    edpm_old_tripleo_services: "{{ edpm_libvirt_old_tripleo_compute_sevices }}"
  when: edpm_libvirt_old_tripleo_compute_sevices | default([]) | length > 0
