---
- name: Gather Ceph configuration files
  tags:
    - install
    - post-libvirt
    - ceph
  become: true
  ansible.builtin.find:
    paths: "{{ edpm_libvirt_ceph_path }}"
    patterns: "*.conf"
  register: found_confs

- name: Update Ceph Libvirt secret if Ceph files were found
  tags:
    - install
    - post-libvirt
    - ceph
  become: true
  when:
    - found_confs.files is defined
    - found_confs.files | length > 0
  block:
    - name: Extract FSIDs from Ceph configuration files
      ansible.builtin.shell: |
        echo {{ (item | basename).split('.')[0] }}
        awk -F '=' '/fsid/ {print $2}' {{ item }} | xargs
      register: fsids
      loop: "{{ found_confs.files | map(attribute='path') }}"

    - name: Map Ceph clusters to FSIDs
      ansible.builtin.set_fact:
        cluster_fsid_map: "{{ cluster_fsid_map | default({}) |\
          combine({item.stdout_lines[0] : item.stdout_lines[1] }) }}"
      loop: "{{ fsids.results }}"

    - name: Gather Ceph keyring files
      ansible.builtin.find:
        paths: "{{ edpm_libvirt_ceph_path }}"
        patterns: "*.keyring"
      register: found_keys

    - name: Map Ceph clusters to cephx users
      ansible.builtin.set_fact:
        cluster_user_map: "{{ cluster_user_map | default({}) |\
          combine({item.split('.')[0] : item.split('.')[2] }) }}"
      loop: "{{ found_keys.files | map(attribute='path') | map('basename') }}"

    - name: Use maps to create libvirt secrets
      ansible.builtin.include_tasks: virsh-secret.yml
      vars:
        cluster: "{{ item }}"
        fsid: "{{ cluster_fsid_map[item] }}"
        user: "{{ cluster_user_map[item] }}"
      loop: "{{ cluster_fsid_map.keys() | list }}"

- name: Copy qemu vnc firewall config
  tags:
    - install
    - post-libvirt
  become: true
  ansible.builtin.template:
    src: "firewall.yaml"
    dest: "/var/lib/edpm-config/firewall/vnc.yaml"
    mode: "640"
- name: Configure firewall for the vnc
  tags:
    - install
    - post-libvirt
  ansible.builtin.include_role:
      name: osp.edpm.edpm_nftables
      tasks_from: "configure.yml"
- name: Reload firewall for new vnc rule
  tags:
    - install
    - post-libvirt
  ansible.builtin.include_role:
      name: osp.edpm.edpm_nftables
      tasks_from: "run.yml"
