---
- name: Configure libvirt user and group on the host
  ansible.builtin.import_role:
    name: edpm_users
  vars:
    edpm_users_users:
      # 42473 is matching with the uid and gid created by kolla in the libvirt containers
      - {"name": "libvirt", "uid": "42473", "gid": "42473", "shell": "/sbin/nologin", "comment": "libvirt user"}
    edpm_users_extra_dirs: []
  tags:
    - edpm_users
