---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: instance
provisioner:
  log: true
  name: ansible
  inventory:
    host_vars:
      instance:
        ctlplane_ip: "10.0.0.1"

scenario:
  test_sequence:
  - dependency
  - destroy
  - create
  - prepare
  - converge
  - destroy
verifier:
  name: ansible
