---

- name: Download tuned
  ansible.builtin.dnf:
    name: "{{ edpm_tuned_system_packages }}"
    download_only: true
  become: true
  register: edpm_tuned_system_packages_download
  until: edpm_tuned_system_packages_download.rc == 0
  retries: "{{ edpm_tuned_download_retries }}"
  delay: "{{ edpm_tuned_download_delay }}"
