---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: podman
platforms:
- command: /sbin/init
  dockerfile: ../../../../molecule/common/Containerfile.j2
  image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
  name: fake-networker-1
  privileged: true
  registry:
    url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
  ulimits:
  - host
provisioner:
  log: true
  name: ansible
  inventory:
    hosts:
      all:
        hosts:
          fake-networker-1:
            canonical_hostname: edpm-0.localdomain
scenario:
  test_sequence:
  - dependency
  - destroy
  - create
  - prepare
  - converge
  - verify
  - destroy
verifier:
  name: testinfra
  options:
    s: true
