---
- name: Verify
  hosts: all
  tasks:
    - name: Include default tasks
      ansible.builtin.include_tasks:
        file: ../default/verify-tasks.yml

    - name: Verify hw-offload
      ansible.builtin.shell: >
        /usr/bin/ovs-vsctl get open_vswitch . other_config:hw-offload
      register: output
      failed_when: output.stdout != "True"
