---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
  tasks:
    - name: lookup all host_users
      ansible.builtin.shell: "getent passwd | awk -F':' '{print $1}'"
      register: host_users
      changed_when: false
      failed_when: false
      check_mode: false
    - name: assert expected host_users exist
      ansible.builtin.assert:
        that:
          - item in host_users.stdout_lines
        fail_msg: "User {{ item }} does not exist"
      loop:
        - "qemu"
        - "libvirt"
        - "nova"
    - name: lookup all host_groups
      ansible.builtin.shell: "getent group | awk -F':' '{print $1}'"
      register: host_groups
      changed_when: false
      failed_when: false
      check_mode: false
    - name: assert expected host_groups exist
      ansible.builtin.assert:
        that:
          - item in host_groups.stdout_lines
        fail_msg: "group {{ item }} does not exist"
      loop:
        - "qemu"
        - "hugetlbfs"
        - "libvirt"
        - "nova"
    - name: ensure expected directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_dir.yaml"
      loop:
        - /var/lib/vhost_sockets

    - name: Lookup libvirt group
      ansible.builtin.getent:
        database: group
        key: libvirt
      register: libvirt_group

    - name: Assert that nova is in the libvirt group
      ansible.builtin.assert:
        that:
          # 2: the users in the group
          - "'nova' in libvirt_group.ansible_facts.getent_group.libvirt[2]"
