---
argument_specs:
  # ./roles/edpm_ceph_client_files/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_ceph_client_files role.
    options:
      edpm_ceph_client_files_config_home:
        default: '{{ edpm_ceph_client_config_home | default(''/var/lib/openstack/config/ceph'') }}'
        description: Destination of ceph files on the remote machine.
        type: str
      edpm_ceph_client_files_source:
        default: /etc/ceph
        description: Location of the ceph files on `localhost`
        type: str
