---
argument_specs:
  # ./roles/edpm_ceph_hci_pre/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_ceph_hci_pre role.
    options:
      edpm_ceph_hci_pre_configure_firewall:
        default: true
        description: >-
          Whether or not firewall ports should be opened
          to allow access to Ceph services hosted on the node being
          configured. No firewall configurations are made when `false`.
        type: bool
      edpm_ceph_hci_pre_storage_ranges:
        type: list
        description: >-
          List of IP address ranges in CIDR notation which
          can access the Ceph `public_netowrk` firewall ports to be
          opened. Defaults to a list with only the EDPM storage network
          (`172.18.0.0/24`). If the list is empty, then no firewall ports
          are opened. To allow access from all networks add `0.0.0.0/0`
          to the list.
        default: ['172.18.0.0/24']
      edpm_ceph_hci_pre_rgw_frontend_ranges:
        type: list
        description: >-
          List of IP address ranges in CIDR notation which
          can access the frontend Ceph RGW firewall ports to be
          opened. If the list is empty, then no firewall ports are
          opened. To allow access from all networks add `0.0.0.0/0`
          to the list.
        default: []
      edpm_ceph_hci_pre_grafana_frontend_ranges:
        type: list
        description: >-
          List of IP address ranges in CIDR notation which
          can access the frontend Ceph Grafana firewall ports to be
          opened. If the list is empty, then no firewall ports are
          opened. To allow access from all networks add `0.0.0.0/0`
          to the list.
        default: []
      edpm_ceph_hci_pre_rbd_mirror_ranges:
        type: list
        description: >-
          List of IP address ranges in CIDR notation which
          can access the frontend Ceph RBD mirror firewall ports to be
          opened. If the list is empty, then no firewall ports are
          opened. To allow access from all networks add `0.0.0.0/0`
          to the list.
        default: []
      edpm_ceph_hci_pre_firewall_services:
        type: list
        description: >-
          List of dictionaries describing each Ceph service name (`name`),
          firewall rule order number (`num`), ranges based on the different
          ranges defined above (for all variables above matching
          `edpm_ceph_hci_pre_*_ranges`), and destination port list (`dport`).
          If the `dport` list contains an interval, e.g. `mix:max`, then all
          ports between (and including) `min` and `max` will be opened.
        default:
          - name: ceph_mon
            num: 110
            dport:
              - 6789
              - 3300
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_osd
            num: 111
            dport:
              - 6800:7300
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_mgr
            num: 113
            dport:
              - 6800:7300
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_mds
            num: 112
            dport:
              - 6800:7300
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_nfs
            num: 120
            dport:
              - 2049
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_rgw
            num: 122
            dport:
              - 8080
              - 13808
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_rgw_frontend
            num: 100
            dport:
              - 8080
            ranges: "{{ edpm_ceph_hci_pre_rgw_frontend_ranges | list }}"
          - name: ceph_ssl_rgw_frontend
            num: 100
            dport:
              - 13808
            ranges: "{{ edpm_ceph_hci_pre_rgw_frontend_ranges | list }}"
          - name: ceph_rbdmirror
            num: 114
            dport:
              - 6800:7300
            ranges: "{{ edpm_ceph_hci_pre_rbd_mirror_ranges | list }}"
          - name: ceph_grafana
            num: 123
            dport:
              - 3100
              - 9100
              - 9090
              - 9092
              - 9093
              - 9094
              - 9100
              - 9283
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_grafana_frontend
            num: 100
            dport:
              - 3100
            ranges: "{{ edpm_ceph_hci_pre_grafana_frontend_ranges | list }}"
          - name: ceph_prometheus
            num: 100
            dport:
              - 9092
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
          - name: ceph_alertmanager
            num: 100
            dport:
              - 9093
            ranges: "{{ edpm_ceph_hci_pre_storage_ranges | list }}"
      edpm_ceph_hci_pre_enabled_services:
        type: list
        description: >-
          List of names matching each `name` in the
          `edpm_ceph_hci_pre_firewall_services` which should have their
          firewall ports opened. By default only the Ceph RBD (block)
          service is configured with it's supporting services. If EDPM
          nodes will host a Ceph cluster with more than just block
          service, then extend this list. If this list is empty, then
          no firewall ports for Ceph will be opened.
        default:
          - ceph_mon
          - ceph_mgr
          - ceph_osd
