---
# defaults file for edpm_ovn

# seconds between retries for download tasks
edpm_neutron_ovn_images_download_delay: 5

# number of retries for download tasks
edpm_neutron_ovn_images_download_retries: 5

edpm_neutron_ovn_config_src: /var/lib/openstack/configs/neutron-ovn
edpm_neutron_ovn_agent_config_dir: /var/lib/config-data/ansible-generated/neutron-ovn-agent
edpm_neutron_ovn_agent_log_dir: "/var/log/neutron"

edpm_neutron_ovn_agent_image: "quay.io/podified-antelope-centos9/openstack-neutron-ovn-agent:current-podified"

edpm_neutron_ovn_common_volumes:
  - /run/openvswitch:/run/openvswitch:z
  - "{{ edpm_neutron_ovn_agent_config_dir }}:/etc/neutron.conf.d:z"
  - /var/log/containers/neutron:/var/log/neutron:z
  - /var/lib/kolla/config_files/ovn_agent.json:/var/lib/kolla/config_files/config.json:ro

# Neutron conf
# DEFAULT
edpm_neutron_ovn_agent_DEFAULT_host: '{{ ansible_facts["nodename"] }}'  # also in missing vars

# rootwrap.conf
edpm_neutron_ovn_agent_rootwrap_DEFAULT_filters_path: '/usr/share/neutron/rootwrap'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_exec_dirs: '/sbin,/usr/sbin,/bin,/usr/bin,/usr/local/bin,/usr/local/sbin'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_use_syslog: 'False'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_syslog_log_facility: 'syslog'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_syslog_log_level: 'ERROR'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_daemon_timeout: '600'
edpm_neutron_ovn_agent_rootwrap_DEFAULT_rlimit_nofile: '1024'

# neutron-ovn-agent.conf
edpm_neutron_ovn_agent_DEFAULT_debug: 'True'
edpm_neutron_ovn_agent_agent_root_helper: 'sudo neutron-rootwrap /etc/neutron.conf.d/01-rootwrap.conf'
edpm_neutron_ovn_agent_ovs_ovsdb_connection: 'tcp:127.0.0.1:6640'
edpm_neutron_ovn_agent_ovs_ovsdb_connection_timeout: '180'
edpm_neutron_ovn_agent_ovn_ovsdb_connection_timeout: '180'
edpm_neutron_ovn_agent_ovn_ovsdb_probe_interval: '60000'
edpm_neutron_ovn_agent_ovn_ovn_nb_connection: ''
edpm_neutron_ovn_agent_ovn_ovn_sb_connection: ''
