galaxy_info:
  role_name: chrony
  author: EDPM team
  description: chrony role
  company: Red Hat
  license: Apache 2.0
  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'

  galaxy_tags:
    - openstack

dependencies: []
