---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: Copy over cacerts
  tags:
    - certs
  become: true
  block:
    - name: Set paths
      ansible.builtin.set_fact:
        cacert_src_path: "/var/lib/openstack/cacerts/{{ service }}"
        cacert_dest_path: "/var/lib/openstack/cacerts/{{ service }}"

    - name: Ensure that the destination directories exist
      ansible.builtin.file:
        path: "{{ cacert_dest_path }}"
        state: "directory"
        setype: "container_file_t"
        owner: "root"
        group: "root"
        mode: "0755"

    - name: Copy cacert to the compute node
      ansible.builtin.copy:
        src: "{{ cacert_src_path }}/tls-ca-bundle.pem"
        dest: "{{ cacert_dest_path }}/tls-ca-bundle.pem"
        mode: '0600'
        owner: root
        group: root
