dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance
    image: "${EDPM_ANSIBLE_MOLECULE_IMAGE:-'ubi9/ubi-init'}"
    registry:
      url: "${EDPM_ANSIBLE_MOLECULE_REGISTRY:-'registry.access.redhat.com'}"
    command: /sbin/init
    dockerfile: "../../../../molecule/common/Containerfile.j2"
    privileged: true
    ulimits:
      - host

provisioner:
  name: ansible
  log: true
  config_options:
    interpreter_python: auto_silent
    callback_whitelist: profile_tasks, timer, yaml
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - destroy

tasks:
  - name: "Include edpm_download_cache"
    include_role:
      name: "osp.edpm.edpm_download_cache"
