command: /usr/local/bin/virtlogd_wrapper
config_files:
  - source: "/var/lib/kolla/config_files/src/*"
    dest: "/"
    merge: true
    preserve_properties: true
  - source: "/var/lib/kolla/config_files/src-ceph/"
    dest: "/etc/ceph/"
    merge: true
    preserve_properties: true
permissions: "{{ edpm_nova_libvirt_ceph_multiconfig_permissions }}"
