---
- name: Downloading required packages
  ansible.builtin.dnf:
    name: "{{ edpm_ovs_packages }}"
    download_only: true
  become: true
  register: _install_packages_result
  until: _install_packages_result.rc == 0
  retries: "{{ edpm_ovs_download_retries }}"
  delay: "{{ edpm_ovs_download_delay }}"
