---
argument_specs:
  # ./roles/edpm_libvirt/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_libvirt role.
    options:
      edpm_libvirt_image_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_libvirt_image_download_retries:
        type: int
        default: 5
      edpm_libvirt_services:
        type: list
        description: The list of libvirt services to run.
        default:
          - "virtlogd"
          - "virtnodedevd"
          - "virtproxyd"
          - "virtqemud"
          - "virtsecretd"
      edpm_libvirt_range:
        type: str
        description: The version range for libvirt package.
        default: ""
      edpm_libvirt_packages:
        type: list
        description: The list of packages to install for libvirt.
        default:
          - libvirt {{edpm_libvirt_range}}
          - libvirt-admin {{edpm_libvirt_range}}
          - libvirt-client {{edpm_libvirt_range}}
          - libvirt-daemon {{edpm_libvirt_range}}
          - qemu-kvm
          - qemu-img
          - libguestfs
          - libseccomp
          - swtpm
          - swtpm-tools
          - edk2-ovmf
          - ceph-common
      edpm_libvirt_ceph_path:
        type: str
        description: The path to the ceph config files.
        default: "/var/lib/openstack/config/ceph"
      edpm_libvirt_tls_certs_enabled:
        type: bool
        default: false
        description: Boolean to specify whether TLS certs are enabled.
