---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
platforms:
  - name: compute-1
    groups:
      - compute
provisioner:
  log: true
  name: ansible
  env:
    # Non versioned package name will result in latest available
    ovs_pre_update_version: rdo-openvswitch
  playbooks:
    prepare: "../common/update/prepare.yml"
    verify: "../common/update/verify.yml"
    cleanup: ../common/update/cleanup.yml
scenario:
  name: update_no_op
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
