_mocked_cmdline: default_hugepagesz=2M hugepagesz=2048 hugepages=10 hugepagesz=4096 hugepages=10
expected_line: 'GRUB_EDPM_HEAT_TEMPLATE_KERNEL_ARGS=" test=1 default_hugepagesz=2M hugepagesz=2048 hugepages=10 hugepagesz=4096 hugepages=10 "'
edpm_kernel_args: test=1 default_hugepagesz=2M hugepagesz=2048 hugepages=10 hugepagesz=4096 hugepages=10
edpm_kernel_hugepages:
  "2048":
    count: "10"
    default: true
  "4096":
    count: "10"
