---
# Copyright 2023 Red Hat, Inc.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: create ceilometer config dirs
  become: true
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: directory
    setype: "{{ item.setype | default('container_file_t') }}"
    owner: '{{ansible_user}}'
    group: '{{ansible_user}}'
    mode: "{{ item.mode | default('750') }}"
    recurse: true
  with_items:
    - { 'path': /var/lib/openstack/config/containers}
    - { 'path': /var/lib/openstack/config/ceilometer}
  tags:
    - edpm_telemetry


- name: create persistent directories
  become: true
  file:
    path: "{{ item.path }}"
    setype: "{{ item.setype | default('container_file_t') }}"
    state: directory
    owner: "{{ item.owner | default(ansible_user) }}"
    group: "{{ item.group | default(ansible_user) }}"
    mode: "{{ item.mode | default(omit) }}"
  with_items:
    - { 'path': /var/log/containers/ceilometer, 'mode': '0750' }
  tags:
    - edpm_telemetry

- name: Copy generated ceilometer configs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('640') }}"
    remote_src: "{{ telemetry_test | default('false') }}"
  with_items:
    - { 'src': "/var/lib/config-data/merged/ceilometer.conf", "dest": "/var/lib/openstack/config/ceilometer/ceilometer.conf" }
    - { 'src': "/var/lib/config-data/merged/polling.yaml", "dest": "/var/lib/openstack/config/ceilometer/polling.yaml" }
    - { 'src': "/var/lib/config-data/merged/ceilometer_agent_compute.json", "dest": "/var/lib/openstack/config/containers/ceilometer_agent_compute.json" }
    - { 'src': "/var/lib/config-data/merged/ceilometer-agent-compute.json", "dest": "/var/lib/openstack/config/ceilometer/ceilometer-agent-compute.json" }
  tags:
    - edpm_telemetry

- name: deploy ceilometer container
  ansible.builtin.include_role:
    name: osp.edpm.edpm_container_manage
  vars:
    edpm_container_manage_config: '/var/lib/openstack/config/containers'
    edpm_container_manage_healthcheck_disabled: true
    edpm_container_manage_config_patterns: 'ceilometer_agent_compute.json'
    edpm_container_manage_clean_orphans: false
  tags:
    - edpm_telemetry

- name: restart ceilometer
  become: true
  ansible.builtin.systemd:
    state: restarted
    name: edpm_ceilometer_agent_compute.service
  tags:
    - edpm_telemetry
