expected_line: 'GRUB_EDPM_KERNEL_ARGS=" test=1 default_hugepagesz=2048 hugepagesz=2048 hugepages=10 "'
_mocked_cmdline: ""
edpm_kernel_args: "test=1"
edpm_kernel_hugepages:
  "2048":
    count: "10"
    default: true
