---
dependency:
  name: galaxy
  options:
    role-file: collections.yml
driver:
  name: podman
platforms:
- command: /sbin/init
  dockerfile: ../../../../molecule/common/Containerfile.j2
  image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
  name: instance
  privileged: true
  registry:
    url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
  ulimits:
  - host
provisioner:
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
  inventory:
    hosts:
      all:
        children:
          allovercloud:
            hosts:
              instance:
                canonical_hostname: centos.localdomain
                ctlplane_hostname: centos.ctlplane.localdomain
                ctlplane_ip: 10.0.0.1
                edpm_role_networks:
                - ctlplane
                - internal_api
                - management
                internal_api_hostname: centos.internalapi.localdomain
                internal_api_ip: 10.0.1.1
                management_ip: 10.0.0.1
        hosts:
          instance:
            ansible_python_interpreter: /usr/bin/python3
  log: true
  name: ansible
scenario:
  test_sequence:
  - destroy
  - create
  - prepare
  - converge
  - check
  - verify
  - destroy
verifier:
  name: testinfra
