---
driver:
  # it starts podman containers to create configs, cannot use podman driver
  name: delegated
  options:
    ansible_connection_options:
      ansible_connection: local
      ansible_host: localhost
platforms:
  - name: instance
    image: ${EDPM_ANSIBLE_MOLECULE_IMAGE:-"ubi9/ubi-init"}
    registry:
      url: ${EDPM_ANSIBLE_MOLECULE_REGISTRY:-"registry.access.redhat.com"}
    command: /sbin/init
    dockerfile: ../../../../molecule/common/Containerfile.j2
    privileged: true
    ulimits: &ulimit
      - host
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
      remote_src: true
  log: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - destroy
