---
argument_specs:
  # ./roles/edpm_swift/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_swift role.
    description: Multiple lines description
    options: {}
