---
- name: Converge
  hosts: all
  tasks:
    - name: Test edpm_telemetry_logging role
      ansible.builtin.include_role:
        name: "osp.edpm.edpm_telemetry_logging"
      vars:
        telemetry_test: true
        ansible_user: root
        ansible_user_dir: /root
