---
- name: Verify
  hosts: all
  tasks:
    - name: Include defaults/main.yml
      ansible.builtin.include_vars: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

    - name: Ensure that 10-neutron-ovn.conf was copied into the container
      block:
        - name: ovn-agent config file exists
          become: true
          ansible.builtin.stat:
            path: "/var/lib/config-data/ansible-generated/neutron-ovn-agent/10-neutron-ovn.conf"
          register: ovn_agent_config

        - name: assert that the config exists
          ansible.builtin.assert:
            that:
              - ovn_agent_config.stat.exists
            fail_msg: "ovn agent config file does not exist"

    - name: Ensure that configured root helper works
      ansible.builtin.shell: |
        podman exec ovn_agent {{ edpm_neutron_ovn_agent_agent_root_helper }} sleep 0
