---

- name: Configure EDPM as client of Ceph
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Configure EDPM as client of Ceph
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ceph_client_files
      tags:
        - edpm_ceph_client
