---

- name: Deploy EDPM Network
  hosts: all
  strategy: linear
  become: true
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    # Sets up network using OVS
    - name: Import edpm_network_config
      ansible.builtin.import_role:
        name: osp.edpm.edpm_network_config
      tags:
        - edpm_network_config
