---

- name: Deploy EDPM Network
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Import edpm_network_config
      ansible.builtin.import_role:
        name: osp.edpm.edpm_network_config
      tags:
        - edpm_network_config
