---

- name: Configure OvS DPDK
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Configure OvS DPDK configs
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovs_dpdk
      tags:
        - edpm_ovs_dpdk
