---

- name: Deploy EDPM Operating System Install
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Install edpm_podman
      ansible.builtin.import_role:
        name: osp.edpm.edpm_podman
        tasks_from: install.yml
      tags:
        - edpm_podman
    - name: Install edpm_sshd
      ansible.builtin.import_role:
        name: osp.edpm.edpm_sshd
        tasks_from: install.yml
      tags:
        - edpm_sshd
    - name: Install edpm_chrony
      ansible.builtin.import_role:
        name: osp.edpm.edpm_chrony
        tasks_from: install.yml
      tags:
        - edpm_chrony
    - name: Install edpm_logrotate_crond
      ansible.builtin.import_role:
        name: osp.edpm.edpm_logrotate_crond
        tasks_from: install.yml
      tags:
        - edpm_logrotate_crond
    - name: Install edpm_iscsid
      ansible.builtin.import_role:
        name: osp.edpm.edpm_iscsid
        tasks_from: install.yml
      tags:
        - edpm_iscsid
    - name: Install edpm_multipathd
      ansible.builtin.import_role:
        name: osp.edpm.edpm_multipathd
        tasks_from: install.yml
      tags:
        - edpm_multipathd
