---

- name: Deploy EDPM libvirt
  hosts: all
  strategy: linear
  tasks:
    - name: Deploy EDPM libvirt
      ansible.builtin.import_role:
        name: osp.edpm.edpm_libvirt
      tags:
        - edpm_libvirt
