---

- name: Deploy EDPM libvirt
  hosts: all
  strategy: linear
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: Deploy EDPM libvirt
      ansible.builtin.import_role:
        name: osp.edpm.edpm_libvirt
      tags:
        - edpm_libvirt
