---

- name: Deploy EDPM Neutron SR-IOV agent
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Neutron SR-IOV agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_neutron_sriov
      tags:
        - edpm_neutron_sriov
