---

- name: Deploy EDPM Nova
  hosts: all
  strategy: linear
  tasks:
    - name: Deploy EDPM Nova
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nova
      tags:
        - edpm_nova
