---

- name: Deploy EDPM OVN
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Deploy EDPM OVN
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovn
      tags:
        - edpm_ovn
