---

- name: Deploy EDPM OVN BGP Agent
  hosts: all
  strategy: linear
  become: true
  any_errors_fatal: "{{ edpm_any_errors_fatal | default(true) }}"
  max_fail_percentage: "{{ edpm_max_fail_percentage | default(0) }}"
  tasks:
    - name: EDPM OVN BGP Agent
      ansible.builtin.import_role:
        name: osp.edpm.edpm_ovn_bgp_agent
      tags:
        - edpm_ovn_bgp_agent
