---

- name: Deploy EDPM FRR Run
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Run edpm_frr
      ansible.builtin.import_role:
        name: osp.edpm.edpm_frr
        tasks_from: run.yml
      tags:
        - edpm_frr
