---

- name: Deploy EDPM Operating System Run
  hosts: all
  strategy: linear
  become: true
  tasks:
    - name: Run edpm_sshd
      ansible.builtin.import_role:
        name: osp.edpm.edpm_sshd
        tasks_from: run.yml
      tags:
        - edpm_sshd
    - name: Run edpm_timezone
      ansible.builtin.import_role:
        name: osp.edpm.edpm_timezone
        tasks_from: run.yml
      tags:
        - edpm_timezone
    - name: Apply nftables configuration
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nftables
        tasks_from: run.yml
      when: deploy_edpm_openstack_run_firewall | default(True) | bool
      tags:
        - edpm_firewall
    - name: Run edpm_logrotate_crond
      ansible.builtin.import_role:
        name: osp.edpm.edpm_logrotate_crond
        tasks_from: run.yml
      tags:
        - edpm_logrotate_crond
    - name: Run edpm_iscsid
      ansible.builtin.import_role:
        name: osp.edpm.edpm_iscsid
        tasks_from: run.yml
      tags:
        - edpm_iscsid
    - name: Run edpm_multipathd
      ansible.builtin.import_role:
        name: osp.edpm.edpm_multipathd
        tasks_from: run.yml
      tags:
        - edpm_multipathd
