---

- name: EDPM Node validation
  hosts: all
  strategy: linear
  tasks:
    - name: Import edpm_nodes_validation
      ansible.builtin.import_role:
        name: osp.edpm.edpm_nodes_validation
      tags:
        - edpm_nodes_validation
