---
argument_specs:
  # ./roles/edpm_nova/tasks/main.yml entry point
  main:
    short_description: The main entry point for the edpm_nova role.
    options:
      edpm_nova_image_download_delay:
        type: int
        default: 5
        description: The seconds between retries for failed download tasks
      edpm_nova_image_download_retries:
        type: int
        default: 5
        description: The number of retries for failed download tasks
      edpm_nova_config_src:
        type: str
        default: /var/lib/openstack/config
        description: |
          The path to the directory containing the nova config files
          in the ansibleEE container. This is the directory
          where all configmaps containing nova config files are mounted.
      edpm_nova_config_dest:
        type: str
        default: /var/lib/openstack/config/nova
        description: |
          The path to the directory where the nova config files
          will be rendered on the compute node.
      edpm_nova_live_migration_tls:
        type: bool
        default: false
        description: Boolean to specify whether live migration TLS is enabled.
      edpm_nova_live_migration_native_tls:
        type: bool
        default: false
        description: Boolean to specify whether live migration NBD TLS is enabled.
      edpm_nova_compute_image:
        type: str
        default: "quay.io/podified-antelope-centos9/openstack-nova-compute:current-podified"
        description: |
          The container image to use for the nova compute container.
          This image is used to create the nova compute container
          on the compute node and generaly will be set via the container
          bundle by the dataplane operator.
      edpm_nova_old_tripleo_compute_sevices:
        type: list
        default:
          - tripleo_nova_compute.service
          - tripleo_nova_migration_target.service
          - tripleo_nova_api_cron.service
          - tripleo_nova_api.service
          - tripleo_nova_conductor.service
          - tripleo_nova_metadata.service
          - tripleo_nova_scheduler.service
          - tripleo_nova_vnc_proxy.service
        description: |
          List of tripleo nova services to stop during EDPM adoption
