---
- name: Upgrade chronyd package
  ansible.builtin.dnf:
    name: chronyd
    state: latest
    update_only: true
  when: edpm_chrony_manage_package | bool
  register: edpm_chronyd_package_download
  until: edpm_chronyd_package_download.rc == 0
  retries: "{{ edpm_chrony_download_retries }}"
  delay: "{{ edpm_chrony_download_delay }}"
  notify: Restart chronyd
