---
- name: Verify neutron-sriov-agent
  gather_facts: false
  hosts: all
  vars:
    test_helper_dir: "../../../../molecule/test-helpers"
  tasks:
    - name: Include defaults/main.yml
      ansible.builtin.include_vars: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/main.yml"

    - name: ensure expected directories exist
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_dir.yaml"
      loop:
        - "/var/lib/neutron"
        - "/var/lib/openstack/config/containers"
        - "/var/lib/kolla/config_files/neutron_sriov_agent.json"
        - "/var/lib/config-data/ansible-generated/neutron-sriov-agent"
        - "/var/log/containers/neutron"
        - "/var/log/containers/stdouts"

    - name: ensure systemd services are defined and functional
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_systemd_unit.yaml"
      loop:
        - {"name": "edpm_neutron_sriov_agent.service"}

    - name: ensure podman container exists and are running
      ansible.builtin.include_tasks: "{{test_helper_dir}}/verify_podman.yaml"
      loop:
        - "neutron_sriov_agent"

    - name: ensure that log file for neutron-sriov-agent exist
      become: true
      block:
        - name: Check if file /var/log/containers/neutron/neutron-sriov-nic-agent.log exist
          ansible.builtin.stat:
            path: /var/log/containers/neutron/neutron-sriov-nic-agent.log
          register: log_file
        - name: Assert file /var/log/containers/neutron/neutron-sriov-nic-agent.log exist
          ansible.builtin.assert:
            that:
              - log_file.stat.exists
            fail_msg: "File /var/log/containers/neutron/neutron-sriov-nic-agent.log does not exist"

    - name: Ensure that 10-neutron-sriov.conf was copied into the container
      block:
        - name: sriov config file exists
          become: true
          ansible.builtin.stat:
            path: "/var/lib/config-data/ansible-generated/neutron-sriov-agent/10-neutron-sriov.conf"
          register: sriov_config

        - name: assert that the config exists
          ansible.builtin.assert:
            that:
              - sriov_config.stat.exists
            fail_msg: "sriov agent config file does not exist"

    - name: Ensure that configured root helper works
      ansible.builtin.shell: |
        podman exec neutron_sriov_agent {{ edpm_neutron_sriov_agent_AGENT_root_helper }} sleep 0

    - name: Slurp host specific config
      ansible.builtin.slurp:
        src: /var/lib/config-data/ansible-generated/neutron-sriov-agent/01-neutron-sriov-agent.conf
      register: host_specific_config

    - name: Assert that host is rendered into the host specific config
      ansible.builtin.assert:
        that:
          - "'edpm-0.localdomain' in host_specific_config.content | b64decode"
